### ISSUE TITLE
Liuli 项目需要一个 logo

### ISSUE THREAD

**Issue by howie6879** [liuli-io/liuli#23]
项目名称来源，群友 @ Sngxpro 提供：

```txt
代号：琉璃（Liuli）

英文：RuriElysion
 or：RuriWorld

slogan：琉璃开净界，薜荔启禅关 ---梅尧臣《缑山子晋祠 会善寺》

寓意：构建一方净土如东方琉璃净世界。《药师经》云：「然彼佛土，一向清净，无有女人，亦无恶趣，及苦音声。」
```

**Comment by aYuhangZhang** [comment]
![2c_logo](https://user-images.githubusercontent.com/1082616/147537301-6d35c70b-e54e-4f6a-9149-c8bfc73f1635.png)

**Comment by howie6879** [comment]
@aYuhangZhang 我觉得思路不错，但是现在可能想换个名字，如果不换名字可能采取你的思路，另外如果你对名字有啥想法，欢迎留言。

**Comment by howie6879** [comment]
@aYuhangZhang 换新名字了，logo有什么创意吗？

**Comment by aYuhangZhang** [comment]
好名字！有深意。 创意不敢~ 抛第二块转开个头吧

![image](https://user-images.githubusercontent.com/1082616/147675349-c15f9d83-9225-45ab-9e68-a6fbdf0edbf3.png)

**Comment by howie6879** [comment]
@aYuhangZhang 谢谢回复，辛苦了

你这个想法我也考虑过，但是字母感觉有点老气

目前想法是实物画，琉璃这类让我想起了莲花，所以我准备实例化一个莲花，然后用不同颜色的花瓣拼成一个莲花形成logo，类似ios相册的logo

![image](https://user-images.githubusercontent.com/17047388/147675732-694447ac-ff06-4d98-8827-15b8a9da8416.png)

**Comment by aYuhangZhang** [comment]
@howie6879 你这个更酷 更琉璃 👍

**Comment by howie6879** [comment]
![3351644418200_ pic_hd](https://user-images.githubusercontent.com/17047388/153239160-a3d03b08-431f-4e53-9780-ddefce32c9f9.jpg)
