### ISSUE TITLE
抓取公众号文章时，时间格式清洗出错

### ISSUE THREAD

**Issue by showthesunli** [liuli-io/liuli#46]
测试脚本如下：
```
from src.collector.wechat_feddd.start import WeiXinSpider
WeiXinSpider.request_config = {"RETRIES": 3, "DELAY": 5, "TIMEOUT": 20}
WeiXinSpider.start_urls = ['https://mp.weixin.qq.com/s/OrCRVCZ8cGOLRf5p5avHOg']
WeiXinSpider.start()
```

错误原因：
数据清洗时，期望的数据格式是 `2022-03-21 20:59`，但实际抓取回来的数据是 `2022-03-22 20:37:12`，导致 `clean_doc_ts`函数报错。如下图
![image](https://user-images.githubusercontent.com/3203516/159485884-e3c0c98e-83fe-41c6-b2b2-a83f7993ce7a.png)

**Comment by howie6879** [comment]
是 bug，时间提取将更换成从js脚本直接提取：

![image](https://user-images.githubusercontent.com/17047388/159504730-c0b5c736-1f7e-4c85-8137-64e2f51d6547.png)

**Comment by howie6879** [comment]
已修复，更新景镜像重新启动即可：

```shell
docker pull liuliio/schedule:v0.2.3
```
