### ISSUE TITLE
希望能在RSS订阅里面包含~原始文章链接

### ISSUE THREAD

**Issue by CenBoMin** [liuli-io/liuli#53]
![image](https://user-images.githubusercontent.com/75375782/168447299-9a1fed23-b641-49c7-aaac-5c41a4ccd8d3.png)

目前打算写一个脚本，通过全文获取API来去获取全文，在根据自定义的格式寄给我的gmail...这样除了newsletter之外，一些RSS订阅和微信公众号都可以直接在spark阅读...

然而我找到的全文获取的付费api要求有些高，RSS里面的link格式不行，就算经过decodeURIComponent函数转换也还是格式不正确。

如果RSS订阅有原始网页的连接，就可以抓取用原始链接来获取全文而不会出错！

希望作者可以给与支持！感谢：）

**Comment by howie6879** [comment]
mongodb已经存储了全文，你直接拿就行，没必要那么麻烦自己重新抓取。

**Comment by CenBoMin** [comment]
谢谢!我在研究研究！

**Comment by YsMox** [comment]
> mongodb已经存储了全文，你直接拿就行，没必要那么麻烦自己重新抓取。

```html
<feed xmlns="http://www.w3.org/2005/Atom">
<id>腾讯技术</id>
<title>腾讯技术</title>
<updated>2022-05-16T17:54:22.438329+00:00</updated>
<author>
<name>Liuli</name>
</author>
<generator uri="https://github.com/liuli-io/liuli" version="v0.2.4">Liuli</generator>
<entry>
<id>liuli_wechat - 腾讯技术 - 遇到困难，你可以喊“救命”</id>
<title>遇到困难，你可以喊“救命” </title>
<updated>2022-05-16T17:54:22.438643+00:00</updated>
<author>
<name>liuli_wechat - 鹅厂程序员</name>
</author>
<content/>
<link href="/liuli_wechat/腾讯技术/%E9%81%87%E5%88%B0%E5%9B%B0%E9%9A%BE%EF%BC%8C%E4%BD%A0%E5%8F%AF%E4%BB%A5%E5%96%8A%E2%80%9C%E6%95%91%E5%91%BD%E2%80%9D.html" rel="alternate"/>
<published>2022-05-13T13:18:27+08:00</published>
</entry>
</feed>
```
@howie6879 
以上是我使用该项目生成的rss信息。
请问要如何才能获得原始文章链接？希望在<link>中能显示原始文章的链接？请问要如何设置？谢谢

**Comment by howie6879** [comment]
@YsMox 

可以在配置文件rss处理器部分修改参数如下：

```json
{
            "func": "to_rss",
            "doc_source_list": ["liuli_wechat"],
            "link_source": "self"

        }
```

注意：如果你的来源是搜狗微信，那么链接有效期只有2h，所以建议用备份链接，不会失效

**Comment by YsMox** [comment]
您发给我的信件已经收到。Your letter to me has been received.
