### ISSUE TITLE
带有空格的公众号采集总是失败

### ISSUE THREAD

**Issue by hackdoors** [liuli-io/liuli#60]
[2022:05:27 08:11:47] INFO  Request <GET: https://weixin.sogou.com/weixin?type=1&query=丁爸20%情报分析师的工具箱&ie=utf8&s_from=input&_sug_=n&_sug_type_=>
liuli_schedule  | [2022:05:27 08:11:48] ERROR SGWechatSpider <Item: Failed to get target_item's value from html.>
liuli_schedule  | Traceback (most recent call last):
liuli_schedule  |   File "/root/.local/share/virtualenvs/code-nY5aaahP/lib/python3.9/site-packages/ruia/spider.py", line 197, in _process_async_callback
liuli_schedule  |     async for callback_result in callback_results:
liuli_schedule  |   File "/data/code/src/collector/wechat/sg_ruia_start.py", line 58, in parse
liuli_schedule  |     async for item in SGWechatItem.get_items(html=html):
liuli_schedule  |   File "/root/.local/share/virtualenvs/code-nY5aaahP/lib/python3.9/site-packages/ruia/item.py", line 127, in get_items
liuli_schedule  |     raise ValueError(value_error_info)
liuli_schedule  | ValueError: <Item: Failed to get target_item's value from html.>

**Comment by howie6879** [comment]
你日志中的链接本来就无法访问，麻烦确定下公众号名称，如果还是无法访问，你把公众号名称发出来我看看测试一下。

**Comment by hackdoors** [comment]
微信公众号：丁爸 情报分析师的工具箱
奇安信 CERT
这两个出问题

**Comment by howie6879** [comment]
https://weixin.sogou.com/weixin?type=1&query=%E4%B8%81%E7%88%B820%%E6%83%85%E6%8A%A5%E5%88%86%E6%9E%90%E5%B8%88%E7%9A%84%E5%B7%A5%E5%85%B7%E7%AE%B1&ie=utf8&s_from=input&_sug_=n&_sug_type_=

这是你日志的链接，你打开看下，和你发的名称 丁爸 情报分析师的工具箱 不一致

**Comment by hackdoors** [comment]
后来我换成了https://weixin.sogou.com/weixin?type=1&query=丁爸情报分析师的工具箱&ie=utf8&s_from=input&_sug_=n&_sug_type_

https://weixin.sogou.com/weixin?type=1&query=丁爸+情报分析师的工具箱&ie=utf8&s_from=input&_sug_=n&_sug_type_

https://weixin.sogou.com/weixin?type=1&query=丁爸情报%20分析师的工具箱&ie=utf8&s_from=input&_sug_=n&_sug_type_

发现还是不行

**Comment by hackdoors** [comment]
[2022:05:27 10:59:06] INFO  Request <GET: https://weixin.sogou.com/weixin?type=1&query=丁爸情报分析师的工具箱&ie=utf8&s_from=input&_sug_=n&_sug_type_=>
liuli_schedule  | [2022:05:27 10:59:06] ERROR SGWechatSpider <Item: Failed to get target_item's value from html.>
liuli_schedule  | Traceback (most recent call last):
liuli_schedule  |   File "/root/.local/share/virtualenvs/code-nY5aaahP/lib/python3.9/site-packages/ruia/spider.py", line 197, in _process_async_callback
liuli_schedule  |     async for callback_result in callback_results:
liuli_schedule  |   File "/data/code/src/collector/wechat/sg_ruia_start.py", line 58, in parse
liuli_schedule  |     async for item in SGWechatItem.get_items(html=html):
liuli_schedule  |   File "/root/.local/share/virtualenvs/code-nY5aaahP/lib/python3.9/site-packages/ruia/item.py", line 127, in get_items
liuli_schedule  |     raise ValueError(value_error_info)
liuli_schedule  | ValueError: <Item: Failed to get target_item's value from html.>
liuli_schedule  | [2022:05:27 10:59:07] INFO  SGWechatSpider Stopping spider: SGWechatSpider
liuli_schedule  | [2022:05:27 10:59:07] INFO  SGWechatSpider Total requests: 1
liuli_schedule  | [2022:05:27 10:59:07] INFO  SGWechatSpider Time usage: 0:00:05.118396
liuli_schedule  | [2022:05:27 10:59:07] INFO  SGWechatSpider Spider finished!
liuli_schedule  | [2022:05:27 10:59:07] INFO  Liuli 🤗 微信公众号文章更新完毕(1/1)!

**Comment by howie6879** [comment]
那应该是bug，我有时间修复

**Comment by howie6879** [comment]
@hackdoors 已修复，待带最新版本Docker镜像打包完成即可更新使用
