### ISSUE TITLE
多人使用，推送消息的时候有人不喜欢我关注的微信公众号

### ISSUE THREAD

**Issue by hackdoors** [liuli-io/liuli#62]
前些日子搭建了这个系统，于是把同事拉过来关注了推送机器人，结果竟然说我关注的微信公众号太多了，天天给他推送一大堆他不喜欢的玩意儿！
![image](https://user-images.githubusercontent.com/48487393/171017011-398286e5-1a99-4cea-8be4-ca02ed99e8dd.png)
希望能针对分发器功能进行不同的人不同的分发，估计比较难，但我相信难不倒大佬们！！！

**Comment by howie6879** [comment]
@hackdoors 已经增加不同分发器过滤不同源名称参数，可实现不同分发器发送不同数据。

```json
"sender": {
        "sender_list": ["wecom"],
        "query_days": 7,
        "delta_time": 3,
        "custom_filter": {
            "wecom": {
                "delta_time": 1,
                "ignore_doc_source_name": [""]
            }
        }
    }
```

等打包新版本更新可直接使用
