### ISSUE TITLE
采集的文章中如果含有视频，就会无法播放

### ISSUE THREAD

**Issue by hackdoors** [liuli-io/liuli#63]
![image](https://user-images.githubusercontent.com/48487393/171020193-f7eec33f-550f-4f7f-b39e-69a61728b6dd.png)
![image](https://user-images.githubusercontent.com/48487393/171020236-dc55fd5b-c42a-4743-9292-62277e335d20.png)

**Comment by howie6879** [comment]
@hackdoors 这是微信的保护机制，图像和视频不允许跨域访问，图像做了一层代理，视频没有做代理，我这边解决不了
